### ISSUE TITLE
Minor clarification!

### ISSUE THREAD

**Issue by CptSpaceToaster** [great-illuminary/tcg-data-pricing#1]
Hi there! Thanks for your work to help make pricing information easier to access! (~~Even if it's just for Lorcana~~)

I maintain [TCGCSV](https://tcgcsv.com), and would recommend making it abundantly clear in the Project titles and descriptions that this information is coming from a cached place... and not _directly_ from TCGPlayer!

TCGPlayer updates its information immediately as sales occur... while TCGCSV only hits the closed API once a day, and caches the results. (around 20:00 UTC)

We're two different entities entirely. One is a large establishment that allows buyers and sellers to connect and purchase cards from each other. I'm just a chatty developer who vendors information _from_ that API in a somewhat public fashion... on my own website.

If I could be so bold, I'd recommend reflecting that sentiment a little more clearly in the project's [README](https://github.com/great-illuminary/tcg-data-pricing/blob/main/README.md?plain=1#L1) and the description in Maven. I personally don't care a whole lot either way... but I don't want to create an environment where people think "that Toaster guy is TCGPlayer"... I'm not.

**Comment by codlab** [comment]
Some clarification here : it's not just for Lorcana, I was gonna do this this way at first and then... switched back to just providing every endpoints, up to the implementations to be making specific sets (the idea is that in the future a mapper would probably be made to automatically create the enums upon synchronisation)

Yup I'll add the information about the cached API 👍

**Comment by CptSpaceToaster** [comment]
Sweet! Thank you so much!
